### ISSUE TITLE
Update to the latest runtime

### ISSUE THREAD

**Issue by Jandev** [Jandev/minifier#5]
These services have been created using an old Azure Functions runtime.

Updating it to the latest runtime & deploying it to the latest Functions runtime in Azure will be a great improvement.

**Comment by muhmuhhum** [comment]
@Jandev so for my understanding i should switch the nuget package Microsoft.NET.Sdk.Functions to version 3.0.9 ?

**Comment by Jandev** [comment]
Yes, that's part of it.
Sorry for not being more clear.

The Function App should also be upgraded to .NET Core, it's written in the full .NET Framework right now.
This will make sure it can be deployed on the latest runtime in Azure and benefit from the platform improvements.

**Comment by Jandev** [comment]
Fixed with PR #13
